### ISSUE TITLE
Arena  problems

### ISSUE THREAD

**Issue by ms1948** [ModelOriented/ArenaR#2]
If I run the example Live Arena as described in https://github.com/ModelOriented/ArenaR  I receive the following error msg:
Error: Not Found

  GitHub response headers suggest no or insufficient scopes
  To create gists you need the `gist` OAuth scope on your token.

**Comment by piotrpiatyszek** [comment]
It seems weird, that live arena causes a `gistr` problem. To be sure, please check if you are using `upload_arena()` or  `run_server()`. Removing `.httr-oauth` file in the project directory maybe will resolve the issue.

**Comment by ms1948** [comment]
Sorry, but I have another problem, if I run the following commands:
library("dplyr")
library("DALEX")
head(titanic_imputed)
library("ranger")
titanic_rf <- ranger(survived ~ .,
                     data = titanic_imputed,
                     probability = TRUE,
                     classification = TRUE)
library("DALEX")
titanic_ex <- explain(
  titanic_rf,
  data = titanic_imputed)
library("arenar")
titanic_ar <- create_arena(live = TRUE) %>%
  push_model(titanic_ex)
run_server(titanic_ar)

I receive this layout :
[image: Screenshot 2020-04-17 at 00.58.53.png]

without any Models

Thanks in advance for your help

**Comment by piotrpiatyszek** [comment]
I don't see the screenshot, but there was a bug in that example. Try to add `y` argument to explain function as below.
```
titanic_ex <- explain(
  titanic_rf,
  y = titaninc_imputed$survived,
  data = titanic_imputed)
```

**Comment by ms1948** [comment]
Piotr,
also applying your suggestion the situation is the same,
I see the Arena screenshot without Models and Plots, in the annex file the
commands, the screenshot and the sessionInfo.

Thanks

**Comment by pbiecek** [comment]
Hi,
I do not see your screenshots,
can you paste here the output from the R console.

Also please check if you are using this code:

```
library("dplyr")
library("DALEX")
head(titanic_imputed)
library("ranger")
titanic_rf <- ranger(survived ~ .,
                     data = titanic_imputed,
                     probability = TRUE,
                     classification = TRUE)
library("DALEX")
titanic_ex <- explain(
  titanic_rf,
  data = titanic_imputed,
  y = titanic_imputed$survived)
library("arenar")
titanic_ar <- create_arena(live = TRUE) %>%
  push_model(titanic_ex)
run_server(titanic_ar)
```

It works for me, and here is my session info

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

other attached packages:
[1] arenar_0.1.5       ranger_0.12.1      dplyr_0.8.5       
[4] DALEXtra_0.1.10    DALEX_1.1.0.2      mlr3learners_0.1.6
[7] mlr3_0.1.8         xtable_1.8-4       readr_1.3.1   
```

**Comment by ms1948** [comment]
Ok, I have used your code and this is the R Console  output, at the end,
the sessionInfo(). In my previous email there was in attach a pdf document
with all this information and the image of the Arena screenshot.:

> library("dplyr")

> library("DALEX")

> head(titanic_imputed)

  gender age class    embarked  fare sibsp parch survived

1   male  42   3rd Southampton  7.11     0     0        0

2   male  13   3rd Southampton 20.05     0     2        0

3   male  16   3rd Southampton 20.05     1     1        0

4 female  39   3rd Southampton 20.05     1     1        1

5 female  16   3rd Southampton  7.13     0     0        1

6   male  25   3rd Southampton  7.13     0     0        1

> library("ranger")

> titanic_rf <- ranger(survived ~ .,

+                      data = titanic_imputed,

+                      probability = TRUE,

+                      classification = TRUE)

> library("DALEX")

> titanic_ex <- explain(

+   titanic_rf,

+   data = titanic_imputed,

+   y = titanic_imputed$survived)

Preparation of a new explainer is initiated

  -> model label       :  ranger  (  default  )

  -> data              :  2207  rows  8  cols

  -> target variable   :  2207  values

  -> data              :  A column identical to the target variable `y` has
been found in the `data`.  (  WARNING  )

  -> data              :  It is highly recommended to pass `data` without
the target variable column

  -> model_info        :  package ranger , ver. 0.12.1 , task
classification (  default  )

  -> predict function  :  yhat.ranger  will be used (  default  )

  -> predicted values  :  numerical, min =  0.0106159 , mean =  0.3225986 ,
max =  0.9917455

  -> residual function :  difference between y and yhat (  default  )

  -> residuals         :  numerical, min =  -0.7793278 , mean =
 -0.0004418275 , max =  0.8820997

  A new explainer has been created!

> library("arenar")

> titanic_ar <- create_arena(live = TRUE) %>%

+   push_model(titanic_ex)

> run_server(titanic_ar)

Starting server to listen on port 8181


> utils::sessionInfo()

R version 3.6.3 (2020-02-29)

Platform: x86_64-apple-darwin15.6.0 (64-bit)

Running under: macOS Catalina 10.15.4


Matrix products: default

BLAS:
/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib

LAPACK:
/Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib


locale:

[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8


attached base packages:

[1] stats     graphics  grDevices utils     datasets  methods

[7] base


other attached packages:

[1] arenar_0.1.6  ranger_0.12.1 DALEX_1.0.1   dplyr_0.8.5


loaded via a namespace (and not attached):

 [1] Rcpp_1.0.4.6     rstudioapi_0.11  magrittr_1.5

 [4] tidyselect_1.0.0 munsell_0.5.0    lattice_0.20-40

 [7] colorspace_1.4-1 R6_2.4.1         rlang_0.4.5

[10] fansi_0.4.1      tools_3.6.3      grid_3.6.3

[13] gtable_0.3.0     cli_2.0.2        ellipsis_0.3.0

[16] assertthat_0.2.1 tibble_3.0.0     lifecycle_0.2.0

[19] crayon_1.3.4     Matrix_1.2-18    later_1.0.0

[22] plumber_0.4.6    purrr_0.3.4      ggplot2_3.3.0

[25] promises_1.1.0   vctrs_0.2.4      glue_1.4.0

[28] stringi_1.4.6    compiler_3.6.3   pillar_1.4.3

[31] scales_1.1.0     jsonlite_1.6.1   httpuv_1.5.2

[34] pkgconfig_2.0.3

**Comment by pbiecek** [comment]
It is a problem with CRAN version of the `DALEX`. Please install the dev version from 
```
devtools::install_github("ModelOriented/DALEX")
```

I will update the CRAN version soon.

**Comment by ms1948** [comment]
Sorry,
but also after the installation of DALEX from GitHub, the situation is the
same, nothing in Arena screenshot.
I have noted that in your sessionInfo arena version is 0.1.5, in my
sessionInfo is 0.1.6, can this difference the cause of the problem ?

Thanks

--Marco

**Comment by pbiecek** [comment]
Hi,

1. probably you are attaching files to an email. These files are not visible at gihub so please upload them directly to the issue, otherwise we do not see it
2. it may not be explained in the documentation, but the `run_server(titanic_ar)` function shall open a webpage with interactive dashboad. The R console will be suspended. If you break the run_server function then the dashboard will not work correctly
3. you may also try this version:

```
library("dplyr")
library("DALEX")
head(titanic_imputed)
library("ranger")
titanic_rf <- ranger(survived ~ .,
                     data = titanic_imputed,
                     probability = TRUE,
                     classification = TRUE)
library("DALEX")
titanic_ex <- explain(
  titanic_rf,
  data = titanic_imputed,
  y = titanic_imputed$survived)
library("arenar")
titanic_ar <- create_arena(live = FALSE) %>%
  push_model(titanic_ex)
upload_arena(titanic_ar)
```

**Comment by piotrpiatyszek** [comment]
Also after `run_server(titanic_ar)` please open [dev version of Arena](https://arena.drwhy.ai/branch/dev/?data=http://localhost:8181/&debug=1). It should print some log to the web console (Option + ⌘ + C on safari, Option + ⌘ + J  on chrome and firefox).

**Comment by ms1948** [comment]
Piotr,
finally, using the commands *create_arena(live=FALSE)* and
*upload_arena(titanic_ar)* , as suggested, the arena screenshot works.
The msg in R console is:
[1] "Data url:
https://gist.githubusercontent.com/ms1948/15328d3d046335a3d4b085972164fb36/raw/985f213b8e3c0f4de3de734384f4abb228ef6bf4/data.json
"
===== Static Arena Summary =====
Models: ranger
Observations:
Variables: gender, age, class, embarked, fare, sibsp, parch
Plots count: 15

I have seen that the Data url: https://..../ms1948/....data.json remain in
the the Arena Source URL list, it is possible to remote it ?

Many thanks for your effort.

Best regards

--Marco

**Comment by piotrpiatyszek** [comment]
More advanced settings will be available in a few days after next Arena release. For now you can use [https://arena.drwhy.ai/?clear_storage=1](https://arena.drwhy.ai/?clear_storage=1) to remove all the data, that Arena store in your browser.

**Comment by ms1948** [comment]
Thanks.
Let me know when the new Arena release will be available.
