### ISSUE TITLE
flip the axes in Variable Against Another

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/ArenaR#6]
It would be useful to have the Variable Against Another plot with flipped X and Y axes to correspond to PDP/ALE

![image](https://user-images.githubusercontent.com/32574004/124383780-9b313880-dcce-11eb-96e6-8ee400d737f6.png)

**Comment by piotrpiatyszek** [comment]
Fliped in https://github.com/ModelOriented/Arena/commit/c02a2f980d5ba2ecf21cd516409eb3425333035e
