### ISSUE TITLE
wrong max_variables in Shapley values with more than one model

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/ArenaR#7]
Not sure if it is a bug, but in this case, we see 2 variables when the setting is 1

![image](https://user-images.githubusercontent.com/32574004/124387903-95dce980-dce0-11eb-9e6e-6e41f35ef088.png)

3 instead of 2:

![image](https://user-images.githubusercontent.com/32574004/124387933-ad1bd700-dce0-11eb-8d65-7855947bab5d.png)

5 instead of 4:

![image](https://user-images.githubusercontent.com/32574004/124387959-c755b500-dce0-11eb-9806-7082747130f6.png)

**Comment by piotrpiatyszek** [comment]
This is expected behavior. Arena takes k most important variables of each model independently.
